package de.augmentia.strandsagents.core.agent;

import de.augmentia.strandsagents.core.ToolExecutor;
import de.augmentia.strandsagents.core.ToolRegistry;
import de.augmentia.strandsagents.core.conversation.ConversationManager;
import de.augmentia.strandsagents.sessions.SessionManager;
import de.augmentia.strandsagents.core.model.agent.AgentResult;
import de.augmentia.strandsagents.core.model.event.TokenEvent;
import de.augmentia.strandsagents.core.plugin.Plugin;
import de.augmentia.strandsagents.core.resilience.ResilienceConfig;
import dev.langchain4j.model.chat.StreamingChatModel;
import java.util.List;
import dev.langchain4j.model.chat.request.ChatRequest;
import dev.langchain4j.model.chat.response.ChatResponse;
import java.time.Instant;
import java.util.concurrent.CompletableFuture;
import java.util.function.Consumer;

/**
 * An extension of {@link Agent} that supports real-time token streaming.
 * <p>
 * This class uses a {@link StreamingChatModel} and allows clients to receive incremental
 * output as it is generated by the LLM. It maintains all capabilities of the base agent,
 * including tool usage and plugin integration.
 * </p>
 */
public class StreamingAgent extends Agent {

    private final StreamingChatModel streamingModel;
    private volatile Consumer<String> currentTokenConsumer;

    /**
     * Constructs a StreamingAgent with only a model.
     *
     * @param streamingModel the streaming chat model to use
     */
    public StreamingAgent(StreamingChatModel streamingModel) {
        super(new StreamingModelBridge(streamingModel));
        this.streamingModel = streamingModel;
    }

    /**
     * Constructs a StreamingAgent with model, registry, and executor.
     *
     * @param streamingModel the streaming chat model to use
     * @param toolRegistry   the registry of available tools
     * @param toolExecutor   the executor for running tool calls
     */
    public StreamingAgent(StreamingChatModel streamingModel, ToolRegistry toolRegistry,
                          ToolExecutor toolExecutor) {
        super(new StreamingModelBridge(streamingModel), toolRegistry, toolExecutor);
        this.streamingModel = streamingModel;
    }

    /**
     * Constructs a StreamingAgent with advanced conversation management.
     *
     * @param streamingModel       the streaming chat model to use
     * @param toolRegistry         the registry of available tools
     * @param toolExecutor         the executor for running tool calls
     * @param conversationManager  manager for chat history and context window
     */
    public StreamingAgent(StreamingChatModel streamingModel, ToolRegistry toolRegistry,
                          ToolExecutor toolExecutor, ConversationManager conversationManager) {
        super(new StreamingModelBridge(streamingModel), toolRegistry, toolExecutor, conversationManager);
        this.streamingModel = streamingModel;
    }

    /**
     * Constructs a StreamingAgent with session management.
     *
     * @param streamingModel       the streaming chat model to use
     * @param toolRegistry         the registry of available tools
     * @param toolExecutor         the executor for running tool calls
     * @param conversationManager  manager for chat history and context window
     * @param sessionManager       manager for persistent sessions
     */
    public StreamingAgent(StreamingChatModel streamingModel, ToolRegistry toolRegistry,
                          ToolExecutor toolExecutor, ConversationManager conversationManager,
                          SessionManager sessionManager) {
        super(new StreamingModelBridge(streamingModel), toolRegistry, toolExecutor,
            conversationManager, sessionManager);
        this.streamingModel = streamingModel;
    }

    /**
     * Constructs a StreamingAgent with resilience configuration.
     *
     * @param streamingModel       the streaming chat model to use
     * @param toolRegistry         the registry of available tools
     * @param toolExecutor         the executor for running tool calls
     * @param conversationManager  manager for chat history and context window
     * @param sessionManager       manager for persistent sessions
     * @param resilienceConfig     configuration for retries and circuit breakers
     */
    public StreamingAgent(StreamingChatModel streamingModel, ToolRegistry toolRegistry,
                          ToolExecutor toolExecutor, ConversationManager conversationManager,
                          SessionManager sessionManager, ResilienceConfig resilienceConfig) {
        super(new StreamingModelBridge(streamingModel), toolRegistry, toolExecutor,
            conversationManager, sessionManager, resilienceConfig);
        this.streamingModel = streamingModel;
    }

    /**
     * Full constructor for StreamingAgent.
     *
     * @param streamingModel       the streaming chat model to use
     * @param toolRegistry         the registry of available tools
     * @param toolExecutor         the executor for running tool calls
     * @param conversationManager  manager for chat history and context window
     * @param sessionManager       manager for persistent sessions
     * @param resilienceConfig     configuration for retries and circuit breakers
     * @param plugins              list of plugins (guardrails, HITL, etc.)
     */
    public StreamingAgent(StreamingChatModel streamingModel, ToolRegistry toolRegistry,
                          ToolExecutor toolExecutor, ConversationManager conversationManager,
                          SessionManager sessionManager, ResilienceConfig resilienceConfig,
                          List<Plugin> plugins) {
        super(new StreamingModelBridge(streamingModel), toolRegistry, toolExecutor,
            conversationManager, sessionManager, resilienceConfig, plugins);
        this.streamingModel = streamingModel;
    }

    /**
     * Executes a prompt and streams tokens to the provided handler.
     *
     * @param prompt       the user input text
     * @param tokenHandler a consumer that receives incremental text chunks
     * @return the final execution result
     */
    public AgentResult executeStreaming(String prompt, Consumer<String> tokenHandler) {
        currentTokenConsumer = tokenHandler;
        try {
            return execute(prompt);
        } finally {
            currentTokenConsumer = null;
        }
    }

    /**
     * Asynchronously executes a prompt and streams tokens.
     *
     * @param prompt       the user input text
     * @param tokenHandler a consumer that receives incremental text chunks
     * @return a future that completes with the final execution result
     */
    public CompletableFuture<AgentResult> executeStreamingAsync(String prompt,
                                                                  Consumer<String> tokenHandler) {
        return CompletableFuture.supplyAsync(() -> executeStreaming(prompt, tokenHandler),
            Agent.VIRTUAL_EXECUTOR);
    }

    @Override
    protected ChatResponse doChat(ChatRequest request) {
        var consumer = currentTokenConsumer;
        var bridge = new StreamingModelBridge(streamingModel, token -> {
            fire(new TokenEvent(getSessionId(), Instant.now(), token));
            if (consumer != null) {
                consumer.accept(token);
            }
        });
        return bridge.chat(request);
    }

    public StreamingChatModel getStreamingModel() {
        return streamingModel;
    }
}
