quarkus.http.port=8099
quarkus.http.host=0.0.0.0

quarkus.mcp.server.http.root-path=/mcp

quarkus.mcp.server.server-info.name=Strands Agents MCP Server
quarkus.mcp.server.server-info.version=0.1.1

# quarkus.arc.exclude-dependency.protobuf.group-id=com.google.protobuf
quarkus.arc.exclude-types=com.google.protobuf.*,de.augmentia.strandsagents.mcp.server.tools.*

strands.mcp.server.cwd=${user.dir}
